on:
  push:
      branches: [ main ]

jobs:
  myJob:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/hardware/cpu/units.yaml

