on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  myJob:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/hardware/cpu/units.yaml

